version: 2.1

orbs:
  ruby: g2crowd/ruby@0.0.13

workflows:
  version: 2
  build:
    jobs:
      - ruby/build:
          context: g2crowd-global
          ruby: '2.7.2'
          postgres: '12.4'
          bundler-version: '2.1.4'
