version: 2.1

orbs:
  ruby: g2crowd/ruby@0.1.0

workflows:
  version: 2
  build:
    jobs:
      - ruby/appraisal:
          context: g2crowd-global
          bundler-version: '2.3.9'
          postgres: '12.9'
          setup-database: true
          matrix:
            parameters:
              ruby: ['2.7.5', '3.0.3', '3.1.1']
              appraisal:
                - rails_6.0
                - rails_6.1
                - rails_7.0
