version: 2.1

orbs:
  ruby: g2crowd/ruby@0.0.4

workflows:
  version: 2
  build:
    jobs:
      - ruby/build:
          context: g2crowd-global
          ruby: '2.6.6'
          redis: '2.8'
          postgres: '12.2'
