version: 2.1

orbs:
  ruby: g2crowd/ruby@0.0.16

workflows:
  version: 2
  build:
    jobs:
      - ruby/appraisal:
          context: g2crowd-global
          bundler-version: '2.2.3'
          postgres: '12.4'
          setup-database: true
          matrix:
            parameters:
              ruby: ['2.7.2', '3.0.0']
              appraisal:
                - rails_6.0
                - rails_6.1
