name: Linters

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Rubocop Linter
        uses: g2crowd/rubocop-linter-action@v3.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
